version: "3"

services:
  imageai:
    stdin_open: true # docker run -i
    tty: true 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/imageai
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu